services:
  facefusion:
    build: 
      context: .
      dockerfile: Dockerfile.fast
    container_name: facefusion-intel-gpu
    restart: unless-stopped
    
    # Intel GPU设备映射
    devices:
      - /dev/dri:/dev/dri  # Intel GPU设备
    
    # 环境变量
    environment:
      - OPENVINO_DEVICE=GPU
      - INTEL_OPENVINO_DIR=/usr/local/lib/python3.10/dist-packages/openvino
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    
    # 端口映射
    ports:
      - "7860:7860"
    
    # 卷挂载
    volumes:
      - ./models:/app/.assets/models  # 模型文件持久化
      - ./cache:/app/.caches          # 缓存文件持久化
      - ./output:/app/output          # 输出文件
      - ./input:/app/input            # 输入文件
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11显示支持
    
    # 网络模式
    network_mode: bridge
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# 网络配置
networks:
  default:
    driver: bridge